http_server:
  addres: "0.0.0.0:8090"
  timeout: 4s
  idle_timeout: 60s

storage:
  storage_host: "localhost"
  storage_port: "5432"
  storage_db: "postgres"
  storage_user: "postgres"
  storage_password: "0000"