env: "local" # local, dev, env

http_server:
  addres: "0.0.0.0"
  port: "8088"
  timeout: 4s
  secret: "secret_key"

wishlist:
  gateway_addres: "api_gateway_service"
  gateway_port: "8095"
  api_url: "api/v1"

logbull:
  url: "localhost"
  port: "4005"
  project_id: ""