
networks:
  wishlist_network:
    driver: bridge

volumes:
  zookeeper_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/.volumes/zookeeper/data
  zookeeper_log_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/.volumes/zookeeper/log
  kafka_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/.volumes/kafka/data
  pg_service_auth_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/.volumes/pg_service_auth
  pg_service_wishlist_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/.volumes/pg_service_wishlist
  pg_service_notify_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/.volumes/pg_service_notify
  redis_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/.volumes/redis
  logbull_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/.volumes/logbull

services:
  # ========== POSTGRESS ==========
  # PostgreSQL для Auth Service
  pg_service_auth:
    image: postgres:18-bookworm
    container_name: pg_service_auth
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${AUTH_DB_NAME}
      - POSTGRES_USER=${AUTH_DB_USER}
      - POSTGRES_PASSWORD=${AUTH_DB_PASSWORD}
    volumes:
      - pg_service_auth_volume:/var/lib/postgresql/18/docker
    networks:
      - wishlist_network

  # PostgreSQL для Wishlist Service
  pg_service_wishlist:
    image: postgres:18-bookworm
    container_name: pg_service_wishlist
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=${WISHLIST_DB_NAME}
      - POSTGRES_USER=${WISHLIST_DB_USER}
      - POSTGRES_PASSWORD=${WISHLIST_DB_PASSWORD}
    volumes:
      - pg_service_wishlist_volume:/var/lib/postgresql/18/docker
    networks:
      - wishlist_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U wishlist_user"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  # Redis для кэша и blacklist токенов
  redis_service:
    image: redis:7-alpine
    container_name: redis_service
    ports:
      - "6379:6379"
    volumes:
      - redis_volume:/data
    networks:
      - wishlist_network

  # ========== KAFKA ==========
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: wishlist_zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SYNC_LIMIT: 2
      # Фиксированный ID для Zookeeper
      ZOOKEEPER_SERVER_ID: 1
    ports:
      - "2181:2181"
    volumes:
      - zookeeper_volume:/var/lib/zookeeper/data
      - zookeeper_log_volume:/var/lib/zookeeper/log
    networks:
      - wishlist_network
    healthcheck:
      test: ["CMD", "nc", "-vz", "localhost", "2181"]
      interval: 30s
      timeout: 10s
      retries: 5

  kafka:
    image: confluentinc/cp-kafka:7.3.0
    container_name: wishlist_kafka
    depends_on:
      zookeeper:
        condition: service_healthy
    ports:
      - "${KAFKA_BROKER_PORT}:${KAFKA_BROKER_PORT}"
      - "${KAFKA_BROKER_CONSUMER_PORT}:${KAFKA_BROKER_CONSUMER_PORT}"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:${KAFKA_BROKER_PORT},PLAINTEXT_HOST://kafka:${KAFKA_BROKER_CONSUMER_PORT}
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:${KAFKA_BROKER_PORT},PLAINTEXT_HOST://0.0.0.0:${KAFKA_BROKER_CONSUMER_PORT}

      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_CONFLUENT_TOPIC_REPLICATION_FACTOR: 1
      # Фиксированный cluster ID
      KAFKA_CLUSTER_ID: "wishlist-cluster-2024-01"

    volumes:
      - kafka_volume:/var/lib/kafka/data
    networks:
      - wishlist_network
    healthcheck:
      test: ["CMD", "kafka-topics", "--bootstrap-server", "0.0.0.0:${KAFKA_BROKER_PORT}", "--list"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ========== KAFKA UI ==========
  kafka_ui:
    image: provectuslabs/kafka-ui:latest
    container_name: wishlist_kafka_ui
    depends_on:
      kafka:
        condition: service_healthy
    ports:
      - "${KAFKA_UI_PORT}:${KAFKA_UI_PORT}"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9093 #92
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
      KAFKA_CLUSTERS_0_READONLY: "false"
      KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL: PLAINTEXT
    networks:
      - wishlist_network

  # ========== LOG BULL ==========
  logbull:
    image: logbull/logbull:latest
    container_name: wishlist_logbull
    ports:
      - "${LOGBULL_PORT}:${LOGBULL_PORT}"  # Web UI
    environment:
      - LB_DATA_DIR=/logbull-data
      - LB_PORT=${LOGBULL_PORT} 
      - LB_API_PORT=${LOGBULL_PORT}
    volumes:
      - logbull_volume:/logbull-data
    networks:
      - wishlist_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://0.0.0.0:${LOGBULL_PORT}/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # ========== SERVICES ==========
  auth_service:
    build: ./authService
    container_name: auth_service
    ports:
      - "${AUTH_SERVICE_PORT}:${AUTH_SERVICE_PORT}"
    depends_on:
      - pg_service_auth
      - redis_service
      - kafka
    env_file:
      - .env
    networks:
    - wishlist_network
  wishlist_service:
    build: ./wishlistService
    container_name: wishlist_service
    ports:
      - "${WISHLIST_SERVICE_PORT}:${WISHLIST_SERVICE_PORT}"
    env_file:
      - .env
    networks:
    - wishlist_network
    depends_on:
      pg_service_wishlist:
        condition: service_healthy
      kafka:
        condition: service_healthy
      auth_service:
        condition: service_started
  api_gateway_service:
    build: ./apiGateway
    container_name: api_gateway_service
    ports:
      - "${API_GATEWAY_HTTP_PORT}:${API_GATEWAY_HTTP_PORT}"
    env_file:
      - .env
    networks:
    - wishlist_network
    depends_on:
      - logbull
      - auth_service
      - wishlist_service
      - notification_service
  
  notification_service:
    build: ./notificationService
    container_name: notification_service
    env_file:
      - .env
    networks:
    - wishlist_network
    depends_on:
      kafka:
        condition: service_healthy
