include .env
export

# apiGatewayService
wishlist-apiGateway-run:
	go run cmd/apiGateway/main.go

wishlist-apiGateway-build:
	go build -o .bin/apiGateway cmd/apiGateway/main.go

wishlist-apiGateway-start:
	.bin/apiGateway