// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/login": {
            "post": {
                "description": "Аутентификация пользователя и получение JWT токена",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Вход в систему",
                "parameters": [
                    {
                        "description": "Учетные данные",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.LoginRequestDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешный вход",
                        "schema": {
                            "$ref": "#/definitions/handlers.AuthDTO"
                        }
                    },
                    "400": {
                        "description": "Неверный запрос",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorDTO"
                        }
                    },
                    "401": {
                        "description": "Неверные учетные данные",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorDTO"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorDTO"
                        }
                    }
                }
            }
        },
        "/auth/register": {
            "post": {
                "description": "Создает нового пользователя в системе",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Регистрация пользователя",
                "parameters": [
                    {
                        "description": "Данные для регистрации",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.RegisterRequestDTO"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Успешная регистрация",
                        "schema": {
                            "$ref": "#/definitions/handlers.AuthDTO"
                        }
                    },
                    "400": {
                        "description": "Неверный запрос",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorDTO"
                        }
                    },
                    "409": {
                        "description": "Пользователь уже существует",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorDTO"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorDTO"
                        }
                    }
                }
            }
        },
        "/auth/self": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Возвращает данные аутентифицированного пользователя",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Информация о текущем пользователе",
                "responses": {
                    "200": {
                        "description": "Информация о пользователе",
                        "schema": {
                            "$ref": "#/definitions/handlers.UserInfoDTO"
                        }
                    },
                    "401": {
                        "description": "Не авторизован",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorDTO"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorDTO"
                        }
                    }
                }
            }
        },
        "/bookings": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Возвращает все предметы, забронированные текущим пользователем",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Bookings"
                ],
                "summary": "Бронирования пользователя",
                "responses": {
                    "200": {
                        "description": "Список бронирований",
                        "schema": {
                            "$ref": "#/definitions/handlers.BookingListDTO"
                        }
                    },
                    "401": {
                        "description": "Не авторизован",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorDTO"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorDTO"
                        }
                    }
                }
            }
        },
        "/items/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Возвращает предмет по его ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Items"
                ],
                "summary": "Получить предмет",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID предмета",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Предмет найден",
                        "schema": {
                            "$ref": "#/definitions/handlers.ItemDTO"
                        }
                    },
                    "401": {
                        "description": "Не авторизован",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorDTO"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorDTO"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Обновляет существующий предмет (только владелец вишлиста)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Items"
                ],
                "summary": "Обновить предмет",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID предмета",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Новые данные",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.UpdateItemRequestDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Предмет обновлен",
                        "schema": {
                            "$ref": "#/definitions/handlers.ItemDTO"
                        }
                    },
                    "400": {
                        "description": "Неверный запрос",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorDTO"
                        }
                    },
                    "401": {
                        "description": "Не авторизован",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorDTO"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorDTO"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Удаляет предмет из вишлиста (только владелец)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Items"
                ],
                "summary": "Удалить предмет",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID предмета",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Успешное удаление"
                    },
                    "401": {
                        "description": "Не авторизован",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorDTO"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorDTO"
                        }
                    }
                }
            }
        },
        "/items/{id}/book": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Пользователь бронирует предмет в чужом вишлисте",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Items"
                ],
                "summary": "Забронировать предмет",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID предмета",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Предмет забронирован",
                        "schema": {
                            "$ref": "#/definitions/handlers.ItemDTO"
                        }
                    },
                    "401": {
                        "description": "Не авторизован",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorDTO"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorDTO"
                        }
                    }
                }
            }
        },
        "/items/{id}/unbook": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Отменяет бронирование предмета (бронировавший или владелец)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Items"
                ],
                "summary": "Отменить бронирование",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID предмета",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Бронирование отменено",
                        "schema": {
                            "$ref": "#/definitions/handlers.ItemDTO"
                        }
                    },
                    "401": {
                        "description": "Не авторизован",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorDTO"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorDTO"
                        }
                    }
                }
            }
        },
        "/wishlists": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Создает новый вишлист для текущего пользователя",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Wishlists"
                ],
                "summary": "Создать вишлист",
                "parameters": [
                    {
                        "description": "Данные вишлиста",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.CreateWishlistRequestDTO"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Вишлист создан",
                        "schema": {
                            "$ref": "#/definitions/handlers.WishlistDTO"
                        }
                    },
                    "400": {
                        "description": "Неверный запрос",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorDTO"
                        }
                    },
                    "401": {
                        "description": "Не авторизован",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorDTO"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorDTO"
                        }
                    }
                }
            }
        },
        "/wishlists/public": {
            "get": {
                "description": "Возвращает список публичных вишлистов с пагинацией",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Wishlists"
                ],
                "summary": "Список публичных вишлистов",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Номер страницы",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "Размер страницы",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Список вишлистов",
                        "schema": {
                            "$ref": "#/definitions/handlers.WishlistListDTO"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorDTO"
                        }
                    }
                }
            }
        },
        "/wishlists/user/{user_id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Возвращает все вишлисты указанного пользователя (публичные или все для владельца)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Wishlists"
                ],
                "summary": "Получить вишлисты пользователя",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID пользователя",
                        "name": "user_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Список вишлистов",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/handlers.WishlistListDTO"
                            }
                        }
                    },
                    "401": {
                        "description": "Не авторизован",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorDTO"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorDTO"
                        }
                    }
                }
            }
        },
        "/wishlists/{id}": {
            "get": {
                "description": "Возвращает вишлист по его ID (публичные доступны всем, приватные только владельцу)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Wishlists"
                ],
                "summary": "Получить вишлист",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID вишлиста",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Вишлист найден",
                        "schema": {
                            "$ref": "#/definitions/handlers.WishlistDTO"
                        }
                    },
                    "401": {
                        "description": "Не авторизован для приватного вишлиста",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorDTO"
                        }
                    },
                    "404": {
                        "description": "Вишлист не найден",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorDTO"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorDTO"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Обновляет существующий вишлист (только владелец)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Wishlists"
                ],
                "summary": "Обновить вишлист",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID вишлиста",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Новые данные",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.UpdateWishlistRequestDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Вишлист обновлен",
                        "schema": {
                            "$ref": "#/definitions/handlers.WishlistDTO"
                        }
                    },
                    "400": {
                        "description": "Неверный запрос",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorDTO"
                        }
                    },
                    "401": {
                        "description": "Не авторизован",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorDTO"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorDTO"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Удаляет вишлист и все его предметы (только владелец)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Wishlists"
                ],
                "summary": "Удалить вишлист",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID вишлиста",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Успешное удаление"
                    },
                    "401": {
                        "description": "Не авторизован",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorDTO"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorDTO"
                        }
                    }
                }
            }
        },
        "/wishlists/{wishlist_id}/items": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Возвращает список предметов в указанном вишлисте с пагинацией",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Wishlists"
                ],
                "summary": "Список предметов",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID вишлиста",
                        "name": "wishlist_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Номер страницы",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "Размер страницы",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Список предметов",
                        "schema": {
                            "$ref": "#/definitions/handlers.ItemListDTO"
                        }
                    },
                    "401": {
                        "description": "Не авторизован",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorDTO"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorDTO"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Добавляет новый предмет в указанный вишлист (только владелец)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Wishlists"
                ],
                "summary": "Добавить предмет",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID вишлиста",
                        "name": "wishlist_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Данные предмета",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.CreateItemRequestDTO"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Предмет создан",
                        "schema": {
                            "$ref": "#/definitions/handlers.ItemDTO"
                        }
                    },
                    "400": {
                        "description": "Неверный запрос",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorDTO"
                        }
                    },
                    "401": {
                        "description": "Не авторизован",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorDTO"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorDTO"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handlers.AuthDTO": {
            "type": "object",
            "properties": {
                "expires_at": {
                    "description": "ExpiresAt Время окончания токена (Unix timestamp)\nformat: date-time\nexample: 1700000000",
                    "type": "integer"
                },
                "refresh_token": {
                    "description": "Токен для обновления доступа\nexample: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...",
                    "type": "string"
                },
                "token": {
                    "description": "JWT токен доступа\nexample: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...",
                    "type": "string"
                },
                "user_id": {
                    "description": "UserID UUID пользователя\nformat: uuid\nexample: 123e4567-e89b-12d3-a456-426614174000",
                    "type": "string"
                }
            }
        },
        "handlers.BookingDTO": {
            "type": "object",
            "properties": {
                "booked_at": {
                    "description": "BookedAt Дата и время бронирования\nformat: date-time\nexample: 1700000000",
                    "type": "integer"
                },
                "item_id": {
                    "description": "ItemID UUID айтема\nformat: uuid\nexample: 123e4567-e89b-12d3-a456-426614174000",
                    "type": "string"
                },
                "item_name": {
                    "description": "ItemName Название айтема, доп инфо чтобы не делать лишний запрос позднее\nrequired: true\nminLength: 1\nmaxLength: 80\nexample: Сертификат на метание топоров",
                    "type": "string"
                },
                "user_id": {
                    "description": "UserID UUID пользователя который забронировал айтем\nformat: uuid\nexample: 123e4567-e89b-12d3-a456-426614174000",
                    "type": "string"
                },
                "wishlist_id": {
                    "description": "WishlistID UUID вишлиста в котором находитя айтем\nformat: uuid\nexample: 123e4567-e89b-12d3-a456-426614174000",
                    "type": "string"
                }
            }
        },
        "handlers.BookingListDTO": {
            "type": "object",
            "properties": {
                "bookings": {
                    "description": "Bookings Список бронирований",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handlers.BookingDTO"
                    }
                },
                "total_count": {
                    "description": "TotalCount Общее количество бронирований в списке Bookings\nexample: 100",
                    "type": "integer"
                }
            }
        },
        "handlers.CreateItemRequestDTO": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "description": {
                    "description": "Description Описание айтема\nmaxLength: 1000\nexample: Сертификат, желательно на четверых, и чтобы красивый был и с топорами",
                    "type": "string"
                },
                "image_url": {
                    "description": "ImageURL URL изображения\nformat: uri\nexample: https://example.com/image.jpg",
                    "type": "string"
                },
                "name": {
                    "description": "Name Название айтема\nrequired: true\nminLength: 1\nmaxLength: 80\nexample: Сертификат на метание топоров",
                    "type": "string"
                },
                "price": {
                    "description": "Price Цена в копейках (или предполагаемая цена)\nminimum: 0\nexample: 50000",
                    "type": "integer"
                },
                "product_url": {
                    "description": "ProductURL URL на то где можно приобрести\nformat: uri\nexample: https://example.com/product/123",
                    "type": "string"
                }
            }
        },
        "handlers.CreateWishlistRequestDTO": {
            "type": "object",
            "required": [
                "title"
            ],
            "properties": {
                "description": {
                    "description": "Description Описание вишлиста\nmaxLength: 1000\nexample: Подарки на мой день рождения",
                    "type": "string"
                },
                "is_public": {
                    "description": "IsPublic Флаг публичности вишлиста\nexample: true",
                    "type": "boolean"
                },
                "title": {
                    "description": "Title Название вишлиста\nrequired: true\nminLength: 1\nmaxLength: 80\nexample: На день рождения",
                    "type": "string"
                }
            }
        },
        "handlers.ErrorDTO": {
            "type": "object",
            "properties": {
                "error": {
                    "description": "Error содержит строку с расшифровкой того что пошло не так\nminLength: 1\nmaxLength: 100\nexample: item not found",
                    "type": "string"
                }
            }
        },
        "handlers.ItemDTO": {
            "type": "object",
            "properties": {
                "booked_at": {
                    "description": "BookedAt Дата и время бронирования, если есть\nformat: date-time\nnullable: true\nexample: 1700000000",
                    "type": "integer"
                },
                "booked_by": {
                    "description": "BookedBy UUID пользователя, забронировавшего предмет, если забронирован\nformat: uuid\nnullable: true\nexample: 123e4567-e89b-12d3-a456-426614174000",
                    "type": "string"
                },
                "created_at": {
                    "description": "CreatedAt Дата и время создания (Unix timestamp)\nformat: date-time\nexample: 1700000000",
                    "type": "integer"
                },
                "description": {
                    "description": "Description Описание айтема\nmaxLength: 1000\nexample: Сертификат, желательно на четверых, и чтобы красивый был и с топорами",
                    "type": "string"
                },
                "id": {
                    "description": "ID UUID айтема\nformat: uuid\nexample: 123e4567-e89b-12d3-a456-426614174000",
                    "type": "string"
                },
                "image_url": {
                    "description": "ImageURL URL изображения\nformat: uri\nexample: https://example.com/image.jpg",
                    "type": "string"
                },
                "name": {
                    "description": "Name Название айтема\nrequired: true\nminLength: 1\nmaxLength: 80\nexample: Сертификат на метание топоров",
                    "type": "string"
                },
                "price": {
                    "description": "Price Цена в копейках (или предполагаемая цена)\nminimum: 0\nexample: 50000",
                    "type": "integer"
                },
                "product_url": {
                    "description": "ProductURL URL на то где можно приобрести\nformat: uri\nexample: https://example.com/product/123",
                    "type": "string"
                },
                "updated_at": {
                    "description": "UpdatedAt Дата и время последнего обновления (Unix timestamp)\nformat: date-time\nexample: 1700000000",
                    "type": "integer"
                },
                "wishlist_id": {
                    "description": "ID UUID вишлиста в котором находится айтем\nformat: uuid\nexample: 123e4567-e89b-12d3-a456-426614174000",
                    "type": "string"
                }
            }
        },
        "handlers.ItemListDTO": {
            "type": "object",
            "properties": {
                "current_page": {
                    "description": "CurrentPage Текущая страница\nexample: 1",
                    "type": "integer"
                },
                "items": {
                    "description": "Items Список айтемов",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handlers.ItemDTO"
                    }
                },
                "total_count": {
                    "description": "TotalCount Общее количество айтемов в списке WishlItemsists\nexample: 100",
                    "type": "integer"
                },
                "total_pages": {
                    "description": "TotalPages Общее количество страниц\nexample: 10",
                    "type": "integer"
                }
            }
        },
        "handlers.LoginRequestDTO": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "description": "Email пользователя\nrequired: true\nformat: email\nexample: user@example.com",
                    "type": "string"
                },
                "password": {
                    "description": "Пароль пользователя (минимум 4 символа)\nrequired: true\nminLength: 4\nexample: password123",
                    "type": "string"
                }
            }
        },
        "handlers.RegisterRequestDTO": {
            "type": "object",
            "required": [
                "email",
                "name",
                "password"
            ],
            "properties": {
                "email": {
                    "description": "Email пользователя\nrequired: true\nformat: email\nexample: user@example.com",
                    "type": "string"
                },
                "name": {
                    "description": "Имя, ник пользователя\nrequired: true\nexample: Иван",
                    "type": "string"
                },
                "password": {
                    "description": "Пароль пользователя (минимум 4 символа)\nrequired: true\nminLength: 4\nexample: password123",
                    "type": "string",
                    "minLength": 6
                }
            }
        },
        "handlers.UpdateItemRequestDTO": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "description": {
                    "description": "Description Описание айтема\nmaxLength: 1000\nexample: Сертификат, желательно на четверых, и чтобы красивый был и с топорами",
                    "type": "string"
                },
                "image_url": {
                    "description": "ImageURL URL изображения\nformat: uri\nexample: https://example.com/image.jpg",
                    "type": "string"
                },
                "name": {
                    "description": "Name Название айтема\nrequired: true\nminLength: 1\nmaxLength: 80\nexample: Сертификат на метание топоров",
                    "type": "string"
                },
                "price": {
                    "description": "Price Цена в копейках (или предполагаемая цена)\nminimum: 0\nexample: 50000",
                    "type": "integer"
                },
                "product_url": {
                    "description": "ProductURL URL на то где можно приобрести\nformat: uri\nexample: https://example.com/product/123",
                    "type": "string"
                }
            }
        },
        "handlers.UpdateWishlistRequestDTO": {
            "type": "object",
            "required": [
                "title"
            ],
            "properties": {
                "description": {
                    "description": "Description Описание вишлиста\nmaxLength: 1000\nexample: Подарки на мой день рождения",
                    "type": "string"
                },
                "is_public": {
                    "description": "IsPublic Флаг публичности вишлиста\nexample: true",
                    "type": "boolean"
                },
                "title": {
                    "description": "Title Название вишлиста\nrequired: true\nminLength: 1\nmaxLength: 80\nexample: На день рождения",
                    "type": "string"
                }
            }
        },
        "handlers.UserInfoDTO": {
            "type": "object",
            "properties": {
                "email": {
                    "description": "Email пользователя\nrequired: true\nformat: email\nexample: user@example.com",
                    "type": "string"
                },
                "name": {
                    "description": "Name Имя, ник пользователя\nrequired: true\nexample: Иван",
                    "type": "string"
                },
                "user_id": {
                    "description": "UserID UUID пользователя\nformat: uuid\nexample: 123e4567-e89b-12d3-a456-426614174000",
                    "type": "string"
                }
            }
        },
        "handlers.WishlistDTO": {
            "type": "object",
            "properties": {
                "created_at": {
                    "description": "CreatedAt Дата и время создания (Unix timestamp)\nformat: date-time\nexample: 1700000000",
                    "type": "integer"
                },
                "description": {
                    "description": "Description Описание вишлиста\nmaxLength: 1000\nexample: Подарки на мой день рождения",
                    "type": "string"
                },
                "id": {
                    "description": "ID UUID вишлиста\nformat: uuid\nexample: 123e4567-e89b-12d3-a456-426614174000",
                    "type": "string"
                },
                "is_public": {
                    "description": "IsPublic Флаг публичности вишлиста\nexample: true",
                    "type": "boolean"
                },
                "owner_id": {
                    "description": "OwnerID UUID пользователя - владельца вишлиста\nformat: uuid\nexample: 123e4567-e89b-12d3-a456-426614174000",
                    "type": "string"
                },
                "title": {
                    "description": "Title Название вишлиста\nrequired: true\nminLength: 1\nmaxLength: 80\nexample: На день рождения",
                    "type": "string"
                },
                "updated_at": {
                    "description": "UpdatedAt Дата и время последнего обновления (Unix timestamp)\nformat: date-time\nexample: 1700000000",
                    "type": "integer"
                }
            }
        },
        "handlers.WishlistListDTO": {
            "type": "object",
            "properties": {
                "current_page": {
                    "description": "CurrentPage Текущая страница\nexample: 1",
                    "type": "integer"
                },
                "total_count": {
                    "description": "TotalCount Общее количество вишлистов в списке Wishlists\nexample: 100",
                    "type": "integer"
                },
                "total_pages": {
                    "description": "TotalPages Общее количество страниц\nexample: 10",
                    "type": "integer"
                },
                "wishlists": {
                    "description": "Wishlists Список вишлистов",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handlers.WishlistDTO"
                    }
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Type \"Bearer\" followed by a space and JWT token",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    },
    "tags": [
        {
            "description": "Аутентификация и управление пользователями",
            "name": "Auth"
        },
        {
            "description": "Управление вишлистами",
            "name": "Wishlists"
        },
        {
            "description": "Управление предметами в вишлистах",
            "name": "Items"
        },
        {
            "description": "Бронирование предметов",
            "name": "Bookings"
        }
    ]
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8095",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Wishlist API Gateway",
	Description:      "API Gateway для микросервисного приложения вишлистов",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
