// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: pkg/proto/wishlists/v1/wishlists.proto

package wishlistv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Wishlist messages
type WishlistResponce struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OwnerId       string                 `protobuf:"bytes,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	IsPublic      bool                   `protobuf:"varint,5,opt,name=is_public,json=isPublic,proto3" json:"is_public,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // Unix timestamp
	UpdatedAt     int64                  `protobuf:"varint,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"` // Unix timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WishlistResponce) Reset() {
	*x = WishlistResponce{}
	mi := &file_pkg_proto_wishlists_v1_wishlists_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WishlistResponce) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WishlistResponce) ProtoMessage() {}

func (x *WishlistResponce) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_wishlists_v1_wishlists_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WishlistResponce.ProtoReflect.Descriptor instead.
func (*WishlistResponce) Descriptor() ([]byte, []int) {
	return file_pkg_proto_wishlists_v1_wishlists_proto_rawDescGZIP(), []int{0}
}

func (x *WishlistResponce) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WishlistResponce) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *WishlistResponce) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *WishlistResponce) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *WishlistResponce) GetIsPublic() bool {
	if x != nil {
		return x.IsPublic
	}
	return false
}

func (x *WishlistResponce) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *WishlistResponce) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type CreateWishlistRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	IsPublic      bool                   `protobuf:"varint,4,opt,name=is_public,json=isPublic,proto3" json:"is_public,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWishlistRequest) Reset() {
	*x = CreateWishlistRequest{}
	mi := &file_pkg_proto_wishlists_v1_wishlists_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWishlistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWishlistRequest) ProtoMessage() {}

func (x *CreateWishlistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_wishlists_v1_wishlists_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWishlistRequest.ProtoReflect.Descriptor instead.
func (*CreateWishlistRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_wishlists_v1_wishlists_proto_rawDescGZIP(), []int{1}
}

func (x *CreateWishlistRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateWishlistRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateWishlistRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateWishlistRequest) GetIsPublic() bool {
	if x != nil {
		return x.IsPublic
	}
	return false
}

type GetWishlistRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWishlistRequest) Reset() {
	*x = GetWishlistRequest{}
	mi := &file_pkg_proto_wishlists_v1_wishlists_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWishlistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWishlistRequest) ProtoMessage() {}

func (x *GetWishlistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_wishlists_v1_wishlists_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWishlistRequest.ProtoReflect.Descriptor instead.
func (*GetWishlistRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_wishlists_v1_wishlists_proto_rawDescGZIP(), []int{2}
}

func (x *GetWishlistRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetWishlistRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetUserWishlistsRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	UserId           string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                                 // Чьи вишлисты смотрим
	RequestingUserId string                 `protobuf:"bytes,2,opt,name=requesting_user_id,json=requestingUserId,proto3" json:"requesting_user_id,omitempty"` // Кто запрашивает (для приватных)
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetUserWishlistsRequest) Reset() {
	*x = GetUserWishlistsRequest{}
	mi := &file_pkg_proto_wishlists_v1_wishlists_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserWishlistsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserWishlistsRequest) ProtoMessage() {}

func (x *GetUserWishlistsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_wishlists_v1_wishlists_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserWishlistsRequest.ProtoReflect.Descriptor instead.
func (*GetUserWishlistsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_wishlists_v1_wishlists_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserWishlistsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetUserWishlistsRequest) GetRequestingUserId() string {
	if x != nil {
		return x.RequestingUserId
	}
	return ""
}

type UpdateWishlistRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // Кто обновляет
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	IsPublic      bool                   `protobuf:"varint,5,opt,name=is_public,json=isPublic,proto3" json:"is_public,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateWishlistRequest) Reset() {
	*x = UpdateWishlistRequest{}
	mi := &file_pkg_proto_wishlists_v1_wishlists_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateWishlistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateWishlistRequest) ProtoMessage() {}

func (x *UpdateWishlistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_wishlists_v1_wishlists_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateWishlistRequest.ProtoReflect.Descriptor instead.
func (*UpdateWishlistRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_wishlists_v1_wishlists_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateWishlistRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateWishlistRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateWishlistRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateWishlistRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateWishlistRequest) GetIsPublic() bool {
	if x != nil {
		return x.IsPublic
	}
	return false
}

type DeleteWishlistRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // Кто удаляет
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteWishlistRequest) Reset() {
	*x = DeleteWishlistRequest{}
	mi := &file_pkg_proto_wishlists_v1_wishlists_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteWishlistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteWishlistRequest) ProtoMessage() {}

func (x *DeleteWishlistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_wishlists_v1_wishlists_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteWishlistRequest.ProtoReflect.Descriptor instead.
func (*DeleteWishlistRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_wishlists_v1_wishlists_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteWishlistRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeleteWishlistRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ListPublicWishlistsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPublicWishlistsRequest) Reset() {
	*x = ListPublicWishlistsRequest{}
	mi := &file_pkg_proto_wishlists_v1_wishlists_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPublicWishlistsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPublicWishlistsRequest) ProtoMessage() {}

func (x *ListPublicWishlistsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_wishlists_v1_wishlists_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPublicWishlistsRequest.ProtoReflect.Descriptor instead.
func (*ListPublicWishlistsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_wishlists_v1_wishlists_proto_rawDescGZIP(), []int{6}
}

func (x *ListPublicWishlistsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListPublicWishlistsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type WishlistListResponce struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Wishlists     []*WishlistResponce    `protobuf:"bytes,1,rep,name=wishlists,proto3" json:"wishlists,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	TotalPages    int32                  `protobuf:"varint,3,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	CurrentPage   int32                  `protobuf:"varint,4,opt,name=current_page,json=currentPage,proto3" json:"current_page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WishlistListResponce) Reset() {
	*x = WishlistListResponce{}
	mi := &file_pkg_proto_wishlists_v1_wishlists_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WishlistListResponce) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WishlistListResponce) ProtoMessage() {}

func (x *WishlistListResponce) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_wishlists_v1_wishlists_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WishlistListResponce.ProtoReflect.Descriptor instead.
func (*WishlistListResponce) Descriptor() ([]byte, []int) {
	return file_pkg_proto_wishlists_v1_wishlists_proto_rawDescGZIP(), []int{7}
}

func (x *WishlistListResponce) GetWishlists() []*WishlistResponce {
	if x != nil {
		return x.Wishlists
	}
	return nil
}

func (x *WishlistListResponce) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *WishlistListResponce) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

func (x *WishlistListResponce) GetCurrentPage() int32 {
	if x != nil {
		return x.CurrentPage
	}
	return 0
}

// Item messages
type ItemResponce struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	WishlistId    string                 `protobuf:"bytes,2,opt,name=wishlist_id,json=wishlistId,proto3" json:"wishlist_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,5,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	ProductUrl    string                 `protobuf:"bytes,6,opt,name=product_url,json=productUrl,proto3" json:"product_url,omitempty"`
	Price         int64                  `protobuf:"varint,7,opt,name=price,proto3" json:"price,omitempty"` // копейки
	BookedBy      *string                `protobuf:"bytes,8,opt,name=booked_by,json=bookedBy,proto3,oneof" json:"booked_by,omitempty"`
	BookedAt      *int64                 `protobuf:"varint,9,opt,name=booked_at,json=bookedAt,proto3,oneof" json:"booked_at,omitempty"` // Unix timestamp
	CreatedAt     int64                  `protobuf:"varint,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`   // Unix timestamp
	UpdatedAt     int64                  `protobuf:"varint,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`   // Unix timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemResponce) Reset() {
	*x = ItemResponce{}
	mi := &file_pkg_proto_wishlists_v1_wishlists_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemResponce) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemResponce) ProtoMessage() {}

func (x *ItemResponce) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_wishlists_v1_wishlists_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemResponce.ProtoReflect.Descriptor instead.
func (*ItemResponce) Descriptor() ([]byte, []int) {
	return file_pkg_proto_wishlists_v1_wishlists_proto_rawDescGZIP(), []int{8}
}

func (x *ItemResponce) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ItemResponce) GetWishlistId() string {
	if x != nil {
		return x.WishlistId
	}
	return ""
}

func (x *ItemResponce) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ItemResponce) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ItemResponce) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *ItemResponce) GetProductUrl() string {
	if x != nil {
		return x.ProductUrl
	}
	return ""
}

func (x *ItemResponce) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *ItemResponce) GetBookedBy() string {
	if x != nil && x.BookedBy != nil {
		return *x.BookedBy
	}
	return ""
}

func (x *ItemResponce) GetBookedAt() int64 {
	if x != nil && x.BookedAt != nil {
		return *x.BookedAt
	}
	return 0
}

func (x *ItemResponce) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *ItemResponce) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type AddItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WishlistId    string                 `protobuf:"bytes,1,opt,name=wishlist_id,json=wishlistId,proto3" json:"wishlist_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // Кто добавляет
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,5,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	ProductUrl    string                 `protobuf:"bytes,6,opt,name=product_url,json=productUrl,proto3" json:"product_url,omitempty"`
	Price         int64                  `protobuf:"varint,7,opt,name=price,proto3" json:"price,omitempty"` // копейки
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddItemRequest) Reset() {
	*x = AddItemRequest{}
	mi := &file_pkg_proto_wishlists_v1_wishlists_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddItemRequest) ProtoMessage() {}

func (x *AddItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_wishlists_v1_wishlists_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddItemRequest.ProtoReflect.Descriptor instead.
func (*AddItemRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_wishlists_v1_wishlists_proto_rawDescGZIP(), []int{9}
}

func (x *AddItemRequest) GetWishlistId() string {
	if x != nil {
		return x.WishlistId
	}
	return ""
}

func (x *AddItemRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AddItemRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddItemRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AddItemRequest) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *AddItemRequest) GetProductUrl() string {
	if x != nil {
		return x.ProductUrl
	}
	return ""
}

func (x *AddItemRequest) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

type GetItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // Кто смотрит
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetItemRequest) Reset() {
	*x = GetItemRequest{}
	mi := &file_pkg_proto_wishlists_v1_wishlists_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemRequest) ProtoMessage() {}

func (x *GetItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_wishlists_v1_wishlists_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetItemRequest.ProtoReflect.Descriptor instead.
func (*GetItemRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_wishlists_v1_wishlists_proto_rawDescGZIP(), []int{10}
}

func (x *GetItemRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetItemRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type UpdateItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // Кто обновляет
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,5,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	ProductUrl    string                 `protobuf:"bytes,6,opt,name=product_url,json=productUrl,proto3" json:"product_url,omitempty"`
	Price         int64                  `protobuf:"varint,7,opt,name=price,proto3" json:"price,omitempty"` // копейки
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateItemRequest) Reset() {
	*x = UpdateItemRequest{}
	mi := &file_pkg_proto_wishlists_v1_wishlists_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateItemRequest) ProtoMessage() {}

func (x *UpdateItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_wishlists_v1_wishlists_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateItemRequest.ProtoReflect.Descriptor instead.
func (*UpdateItemRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_wishlists_v1_wishlists_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateItemRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateItemRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateItemRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateItemRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateItemRequest) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *UpdateItemRequest) GetProductUrl() string {
	if x != nil {
		return x.ProductUrl
	}
	return ""
}

func (x *UpdateItemRequest) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

type DeleteItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // Кто удаляет
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteItemRequest) Reset() {
	*x = DeleteItemRequest{}
	mi := &file_pkg_proto_wishlists_v1_wishlists_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteItemRequest) ProtoMessage() {}

func (x *DeleteItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_wishlists_v1_wishlists_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteItemRequest.ProtoReflect.Descriptor instead.
func (*DeleteItemRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_wishlists_v1_wishlists_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteItemRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeleteItemRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ListItemsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WishlistId    string                 `protobuf:"bytes,1,opt,name=wishlist_id,json=wishlistId,proto3" json:"wishlist_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // Кто смотрит
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListItemsRequest) Reset() {
	*x = ListItemsRequest{}
	mi := &file_pkg_proto_wishlists_v1_wishlists_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListItemsRequest) ProtoMessage() {}

func (x *ListItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_wishlists_v1_wishlists_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListItemsRequest.ProtoReflect.Descriptor instead.
func (*ListItemsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_wishlists_v1_wishlists_proto_rawDescGZIP(), []int{13}
}

func (x *ListItemsRequest) GetWishlistId() string {
	if x != nil {
		return x.WishlistId
	}
	return ""
}

func (x *ListItemsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListItemsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListItemsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ItemListResponce struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*ItemResponce        `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	TotalPages    int32                  `protobuf:"varint,3,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	CurrentPage   int32                  `protobuf:"varint,4,opt,name=current_page,json=currentPage,proto3" json:"current_page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemListResponce) Reset() {
	*x = ItemListResponce{}
	mi := &file_pkg_proto_wishlists_v1_wishlists_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemListResponce) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemListResponce) ProtoMessage() {}

func (x *ItemListResponce) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_wishlists_v1_wishlists_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemListResponce.ProtoReflect.Descriptor instead.
func (*ItemListResponce) Descriptor() ([]byte, []int) {
	return file_pkg_proto_wishlists_v1_wishlists_proto_rawDescGZIP(), []int{14}
}

func (x *ItemListResponce) GetItems() []*ItemResponce {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ItemListResponce) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ItemListResponce) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

func (x *ItemListResponce) GetCurrentPage() int32 {
	if x != nil {
		return x.CurrentPage
	}
	return 0
}

// Booking messages
type BookItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        string                 `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // Кто бронирует
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookItemRequest) Reset() {
	*x = BookItemRequest{}
	mi := &file_pkg_proto_wishlists_v1_wishlists_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookItemRequest) ProtoMessage() {}

func (x *BookItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_wishlists_v1_wishlists_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookItemRequest.ProtoReflect.Descriptor instead.
func (*BookItemRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_wishlists_v1_wishlists_proto_rawDescGZIP(), []int{15}
}

func (x *BookItemRequest) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *BookItemRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type UnbookItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        string                 `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // Кто отменяет
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnbookItemRequest) Reset() {
	*x = UnbookItemRequest{}
	mi := &file_pkg_proto_wishlists_v1_wishlists_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnbookItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnbookItemRequest) ProtoMessage() {}

func (x *UnbookItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_wishlists_v1_wishlists_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnbookItemRequest.ProtoReflect.Descriptor instead.
func (*UnbookItemRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_wishlists_v1_wishlists_proto_rawDescGZIP(), []int{16}
}

func (x *UnbookItemRequest) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *UnbookItemRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetBookingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // Чьи бронирования показать
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBookingsRequest) Reset() {
	*x = GetBookingsRequest{}
	mi := &file_pkg_proto_wishlists_v1_wishlists_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBookingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBookingsRequest) ProtoMessage() {}

func (x *GetBookingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_wishlists_v1_wishlists_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBookingsRequest.ProtoReflect.Descriptor instead.
func (*GetBookingsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_wishlists_v1_wishlists_proto_rawDescGZIP(), []int{17}
}

func (x *GetBookingsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetBookingsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetBookingsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type Booking struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        string                 `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	WishlistId    string                 `protobuf:"bytes,2,opt,name=wishlist_id,json=wishlistId,proto3" json:"wishlist_id,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	BookedAt      int64                  `protobuf:"varint,4,opt,name=booked_at,json=bookedAt,proto3" json:"booked_at,omitempty"`
	ItemName      string                 `protobuf:"bytes,5,opt,name=item_name,json=itemName,proto3" json:"item_name,omitempty"` // Для удобства отображения
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Booking) Reset() {
	*x = Booking{}
	mi := &file_pkg_proto_wishlists_v1_wishlists_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Booking) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Booking) ProtoMessage() {}

func (x *Booking) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_wishlists_v1_wishlists_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Booking.ProtoReflect.Descriptor instead.
func (*Booking) Descriptor() ([]byte, []int) {
	return file_pkg_proto_wishlists_v1_wishlists_proto_rawDescGZIP(), []int{18}
}

func (x *Booking) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *Booking) GetWishlistId() string {
	if x != nil {
		return x.WishlistId
	}
	return ""
}

func (x *Booking) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Booking) GetBookedAt() int64 {
	if x != nil {
		return x.BookedAt
	}
	return 0
}

func (x *Booking) GetItemName() string {
	if x != nil {
		return x.ItemName
	}
	return ""
}

type BookingListResponce struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bookings      []*Booking             `protobuf:"bytes,1,rep,name=bookings,proto3" json:"bookings,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookingListResponce) Reset() {
	*x = BookingListResponce{}
	mi := &file_pkg_proto_wishlists_v1_wishlists_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookingListResponce) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookingListResponce) ProtoMessage() {}

func (x *BookingListResponce) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_wishlists_v1_wishlists_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookingListResponce.ProtoReflect.Descriptor instead.
func (*BookingListResponce) Descriptor() ([]byte, []int) {
	return file_pkg_proto_wishlists_v1_wishlists_proto_rawDescGZIP(), []int{19}
}

func (x *BookingListResponce) GetBookings() []*Booking {
	if x != nil {
		return x.Bookings
	}
	return nil
}

func (x *BookingListResponce) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

var File_pkg_proto_wishlists_v1_wishlists_proto protoreflect.FileDescriptor

const file_pkg_proto_wishlists_v1_wishlists_proto_rawDesc = "" +
	"\n" +
	"&pkg/proto/wishlists/v1/wishlists.proto\x12\vwishlist.v1\x1a\x1bgoogle/protobuf/empty.proto\"\xd0\x01\n" +
	"\x10WishlistResponce\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bowner_id\x18\x02 \x01(\tR\aownerId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1b\n" +
	"\tis_public\x18\x05 \x01(\bR\bisPublic\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\x03R\tupdatedAt\"\x85\x01\n" +
	"\x15CreateWishlistRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1b\n" +
	"\tis_public\x18\x04 \x01(\bR\bisPublic\"=\n" +
	"\x12GetWishlistRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"`\n" +
	"\x17GetUserWishlistsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12,\n" +
	"\x12requesting_user_id\x18\x02 \x01(\tR\x10requestingUserId\"\x95\x01\n" +
	"\x15UpdateWishlistRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1b\n" +
	"\tis_public\x18\x05 \x01(\bR\bisPublic\"@\n" +
	"\x15DeleteWishlistRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"M\n" +
	"\x1aListPublicWishlistsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\"\xb8\x01\n" +
	"\x14WishlistListResponce\x12;\n" +
	"\twishlists\x18\x01 \x03(\v2\x1d.wishlist.v1.WishlistResponceR\twishlists\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\x12\x1f\n" +
	"\vtotal_pages\x18\x03 \x01(\x05R\n" +
	"totalPages\x12!\n" +
	"\fcurrent_page\x18\x04 \x01(\x05R\vcurrentPage\"\xe7\x02\n" +
	"\fItemResponce\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vwishlist_id\x18\x02 \x01(\tR\n" +
	"wishlistId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1b\n" +
	"\timage_url\x18\x05 \x01(\tR\bimageUrl\x12\x1f\n" +
	"\vproduct_url\x18\x06 \x01(\tR\n" +
	"productUrl\x12\x14\n" +
	"\x05price\x18\a \x01(\x03R\x05price\x12 \n" +
	"\tbooked_by\x18\b \x01(\tH\x00R\bbookedBy\x88\x01\x01\x12 \n" +
	"\tbooked_at\x18\t \x01(\x03H\x01R\bbookedAt\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\v \x01(\x03R\tupdatedAtB\f\n" +
	"\n" +
	"_booked_byB\f\n" +
	"\n" +
	"_booked_at\"\xd4\x01\n" +
	"\x0eAddItemRequest\x12\x1f\n" +
	"\vwishlist_id\x18\x01 \x01(\tR\n" +
	"wishlistId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1b\n" +
	"\timage_url\x18\x05 \x01(\tR\bimageUrl\x12\x1f\n" +
	"\vproduct_url\x18\x06 \x01(\tR\n" +
	"productUrl\x12\x14\n" +
	"\x05price\x18\a \x01(\x03R\x05price\"9\n" +
	"\x0eGetItemRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"\xc6\x01\n" +
	"\x11UpdateItemRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1b\n" +
	"\timage_url\x18\x05 \x01(\tR\bimageUrl\x12\x1f\n" +
	"\vproduct_url\x18\x06 \x01(\tR\n" +
	"productUrl\x12\x14\n" +
	"\x05price\x18\a \x01(\x03R\x05price\"<\n" +
	"\x11DeleteItemRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"}\n" +
	"\x10ListItemsRequest\x12\x1f\n" +
	"\vwishlist_id\x18\x01 \x01(\tR\n" +
	"wishlistId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"\xa8\x01\n" +
	"\x10ItemListResponce\x12/\n" +
	"\x05items\x18\x01 \x03(\v2\x19.wishlist.v1.ItemResponceR\x05items\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\x12\x1f\n" +
	"\vtotal_pages\x18\x03 \x01(\x05R\n" +
	"totalPages\x12!\n" +
	"\fcurrent_page\x18\x04 \x01(\x05R\vcurrentPage\"C\n" +
	"\x0fBookItemRequest\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\tR\x06itemId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"E\n" +
	"\x11UnbookItemRequest\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\tR\x06itemId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"^\n" +
	"\x12GetBookingsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"\x96\x01\n" +
	"\aBooking\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\tR\x06itemId\x12\x1f\n" +
	"\vwishlist_id\x18\x02 \x01(\tR\n" +
	"wishlistId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x1b\n" +
	"\tbooked_at\x18\x04 \x01(\x03R\bbookedAt\x12\x1b\n" +
	"\titem_name\x18\x05 \x01(\tR\bitemName\"h\n" +
	"\x13BookingListResponce\x120\n" +
	"\bbookings\x18\x01 \x03(\v2\x14.wishlist.v1.BookingR\bbookings\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount2\xd8\b\n" +
	"\x0fWishlistService\x12S\n" +
	"\x0eCreateWishlist\x12\".wishlist.v1.CreateWishlistRequest\x1a\x1d.wishlist.v1.WishlistResponce\x12M\n" +
	"\vGetWishlist\x12\x1f.wishlist.v1.GetWishlistRequest\x1a\x1d.wishlist.v1.WishlistResponce\x12[\n" +
	"\x10GetUserWishlists\x12$.wishlist.v1.GetUserWishlistsRequest\x1a!.wishlist.v1.WishlistListResponce\x12S\n" +
	"\x0eUpdateWishlist\x12\".wishlist.v1.UpdateWishlistRequest\x1a\x1d.wishlist.v1.WishlistResponce\x12L\n" +
	"\x0eDeleteWishlist\x12\".wishlist.v1.DeleteWishlistRequest\x1a\x16.google.protobuf.Empty\x12a\n" +
	"\x13ListPublicWishlists\x12'.wishlist.v1.ListPublicWishlistsRequest\x1a!.wishlist.v1.WishlistListResponce\x12A\n" +
	"\aAddItem\x12\x1b.wishlist.v1.AddItemRequest\x1a\x19.wishlist.v1.ItemResponce\x12A\n" +
	"\aGetItem\x12\x1b.wishlist.v1.GetItemRequest\x1a\x19.wishlist.v1.ItemResponce\x12G\n" +
	"\n" +
	"UpdateItem\x12\x1e.wishlist.v1.UpdateItemRequest\x1a\x19.wishlist.v1.ItemResponce\x12D\n" +
	"\n" +
	"DeleteItem\x12\x1e.wishlist.v1.DeleteItemRequest\x1a\x16.google.protobuf.Empty\x12I\n" +
	"\tListItems\x12\x1d.wishlist.v1.ListItemsRequest\x1a\x1d.wishlist.v1.ItemListResponce\x12C\n" +
	"\bBookItem\x12\x1c.wishlist.v1.BookItemRequest\x1a\x19.wishlist.v1.ItemResponce\x12G\n" +
	"\n" +
	"UnbookItem\x12\x1e.wishlist.v1.UnbookItemRequest\x1a\x19.wishlist.v1.ItemResponce\x12P\n" +
	"\vGetBookings\x12\x1f.wishlist.v1.GetBookingsRequest\x1a .wishlist.v1.BookingListResponceB/Z-wishlistApp/pkg/proto/wishlists/v1;wishlistv1b\x06proto3"

var (
	file_pkg_proto_wishlists_v1_wishlists_proto_rawDescOnce sync.Once
	file_pkg_proto_wishlists_v1_wishlists_proto_rawDescData []byte
)

func file_pkg_proto_wishlists_v1_wishlists_proto_rawDescGZIP() []byte {
	file_pkg_proto_wishlists_v1_wishlists_proto_rawDescOnce.Do(func() {
		file_pkg_proto_wishlists_v1_wishlists_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_wishlists_v1_wishlists_proto_rawDesc), len(file_pkg_proto_wishlists_v1_wishlists_proto_rawDesc)))
	})
	return file_pkg_proto_wishlists_v1_wishlists_proto_rawDescData
}

var file_pkg_proto_wishlists_v1_wishlists_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_pkg_proto_wishlists_v1_wishlists_proto_goTypes = []any{
	(*WishlistResponce)(nil),           // 0: wishlist.v1.WishlistResponce
	(*CreateWishlistRequest)(nil),      // 1: wishlist.v1.CreateWishlistRequest
	(*GetWishlistRequest)(nil),         // 2: wishlist.v1.GetWishlistRequest
	(*GetUserWishlistsRequest)(nil),    // 3: wishlist.v1.GetUserWishlistsRequest
	(*UpdateWishlistRequest)(nil),      // 4: wishlist.v1.UpdateWishlistRequest
	(*DeleteWishlistRequest)(nil),      // 5: wishlist.v1.DeleteWishlistRequest
	(*ListPublicWishlistsRequest)(nil), // 6: wishlist.v1.ListPublicWishlistsRequest
	(*WishlistListResponce)(nil),       // 7: wishlist.v1.WishlistListResponce
	(*ItemResponce)(nil),               // 8: wishlist.v1.ItemResponce
	(*AddItemRequest)(nil),             // 9: wishlist.v1.AddItemRequest
	(*GetItemRequest)(nil),             // 10: wishlist.v1.GetItemRequest
	(*UpdateItemRequest)(nil),          // 11: wishlist.v1.UpdateItemRequest
	(*DeleteItemRequest)(nil),          // 12: wishlist.v1.DeleteItemRequest
	(*ListItemsRequest)(nil),           // 13: wishlist.v1.ListItemsRequest
	(*ItemListResponce)(nil),           // 14: wishlist.v1.ItemListResponce
	(*BookItemRequest)(nil),            // 15: wishlist.v1.BookItemRequest
	(*UnbookItemRequest)(nil),          // 16: wishlist.v1.UnbookItemRequest
	(*GetBookingsRequest)(nil),         // 17: wishlist.v1.GetBookingsRequest
	(*Booking)(nil),                    // 18: wishlist.v1.Booking
	(*BookingListResponce)(nil),        // 19: wishlist.v1.BookingListResponce
	(*emptypb.Empty)(nil),              // 20: google.protobuf.Empty
}
var file_pkg_proto_wishlists_v1_wishlists_proto_depIdxs = []int32{
	0,  // 0: wishlist.v1.WishlistListResponce.wishlists:type_name -> wishlist.v1.WishlistResponce
	8,  // 1: wishlist.v1.ItemListResponce.items:type_name -> wishlist.v1.ItemResponce
	18, // 2: wishlist.v1.BookingListResponce.bookings:type_name -> wishlist.v1.Booking
	1,  // 3: wishlist.v1.WishlistService.CreateWishlist:input_type -> wishlist.v1.CreateWishlistRequest
	2,  // 4: wishlist.v1.WishlistService.GetWishlist:input_type -> wishlist.v1.GetWishlistRequest
	3,  // 5: wishlist.v1.WishlistService.GetUserWishlists:input_type -> wishlist.v1.GetUserWishlistsRequest
	4,  // 6: wishlist.v1.WishlistService.UpdateWishlist:input_type -> wishlist.v1.UpdateWishlistRequest
	5,  // 7: wishlist.v1.WishlistService.DeleteWishlist:input_type -> wishlist.v1.DeleteWishlistRequest
	6,  // 8: wishlist.v1.WishlistService.ListPublicWishlists:input_type -> wishlist.v1.ListPublicWishlistsRequest
	9,  // 9: wishlist.v1.WishlistService.AddItem:input_type -> wishlist.v1.AddItemRequest
	10, // 10: wishlist.v1.WishlistService.GetItem:input_type -> wishlist.v1.GetItemRequest
	11, // 11: wishlist.v1.WishlistService.UpdateItem:input_type -> wishlist.v1.UpdateItemRequest
	12, // 12: wishlist.v1.WishlistService.DeleteItem:input_type -> wishlist.v1.DeleteItemRequest
	13, // 13: wishlist.v1.WishlistService.ListItems:input_type -> wishlist.v1.ListItemsRequest
	15, // 14: wishlist.v1.WishlistService.BookItem:input_type -> wishlist.v1.BookItemRequest
	16, // 15: wishlist.v1.WishlistService.UnbookItem:input_type -> wishlist.v1.UnbookItemRequest
	17, // 16: wishlist.v1.WishlistService.GetBookings:input_type -> wishlist.v1.GetBookingsRequest
	0,  // 17: wishlist.v1.WishlistService.CreateWishlist:output_type -> wishlist.v1.WishlistResponce
	0,  // 18: wishlist.v1.WishlistService.GetWishlist:output_type -> wishlist.v1.WishlistResponce
	7,  // 19: wishlist.v1.WishlistService.GetUserWishlists:output_type -> wishlist.v1.WishlistListResponce
	0,  // 20: wishlist.v1.WishlistService.UpdateWishlist:output_type -> wishlist.v1.WishlistResponce
	20, // 21: wishlist.v1.WishlistService.DeleteWishlist:output_type -> google.protobuf.Empty
	7,  // 22: wishlist.v1.WishlistService.ListPublicWishlists:output_type -> wishlist.v1.WishlistListResponce
	8,  // 23: wishlist.v1.WishlistService.AddItem:output_type -> wishlist.v1.ItemResponce
	8,  // 24: wishlist.v1.WishlistService.GetItem:output_type -> wishlist.v1.ItemResponce
	8,  // 25: wishlist.v1.WishlistService.UpdateItem:output_type -> wishlist.v1.ItemResponce
	20, // 26: wishlist.v1.WishlistService.DeleteItem:output_type -> google.protobuf.Empty
	14, // 27: wishlist.v1.WishlistService.ListItems:output_type -> wishlist.v1.ItemListResponce
	8,  // 28: wishlist.v1.WishlistService.BookItem:output_type -> wishlist.v1.ItemResponce
	8,  // 29: wishlist.v1.WishlistService.UnbookItem:output_type -> wishlist.v1.ItemResponce
	19, // 30: wishlist.v1.WishlistService.GetBookings:output_type -> wishlist.v1.BookingListResponce
	17, // [17:31] is the sub-list for method output_type
	3,  // [3:17] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_pkg_proto_wishlists_v1_wishlists_proto_init() }
func file_pkg_proto_wishlists_v1_wishlists_proto_init() {
	if File_pkg_proto_wishlists_v1_wishlists_proto != nil {
		return
	}
	file_pkg_proto_wishlists_v1_wishlists_proto_msgTypes[8].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_wishlists_v1_wishlists_proto_rawDesc), len(file_pkg_proto_wishlists_v1_wishlists_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_wishlists_v1_wishlists_proto_goTypes,
		DependencyIndexes: file_pkg_proto_wishlists_v1_wishlists_proto_depIdxs,
		MessageInfos:      file_pkg_proto_wishlists_v1_wishlists_proto_msgTypes,
	}.Build()
	File_pkg_proto_wishlists_v1_wishlists_proto = out.File
	file_pkg_proto_wishlists_v1_wishlists_proto_goTypes = nil
	file_pkg_proto_wishlists_v1_wishlists_proto_depIdxs = nil
}
