// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: pkg/proto/wishlists/v1/wishlists.proto

package wishlistv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WishlistService_CreateWishlist_FullMethodName      = "/wishlist.v1.WishlistService/CreateWishlist"
	WishlistService_GetWishlist_FullMethodName         = "/wishlist.v1.WishlistService/GetWishlist"
	WishlistService_GetUserWishlists_FullMethodName    = "/wishlist.v1.WishlistService/GetUserWishlists"
	WishlistService_UpdateWishlist_FullMethodName      = "/wishlist.v1.WishlistService/UpdateWishlist"
	WishlistService_DeleteWishlist_FullMethodName      = "/wishlist.v1.WishlistService/DeleteWishlist"
	WishlistService_ListPublicWishlists_FullMethodName = "/wishlist.v1.WishlistService/ListPublicWishlists"
	WishlistService_AddItem_FullMethodName             = "/wishlist.v1.WishlistService/AddItem"
	WishlistService_GetItem_FullMethodName             = "/wishlist.v1.WishlistService/GetItem"
	WishlistService_UpdateItem_FullMethodName          = "/wishlist.v1.WishlistService/UpdateItem"
	WishlistService_DeleteItem_FullMethodName          = "/wishlist.v1.WishlistService/DeleteItem"
	WishlistService_ListItems_FullMethodName           = "/wishlist.v1.WishlistService/ListItems"
	WishlistService_BookItem_FullMethodName            = "/wishlist.v1.WishlistService/BookItem"
	WishlistService_UnbookItem_FullMethodName          = "/wishlist.v1.WishlistService/UnbookItem"
	WishlistService_GetBookings_FullMethodName         = "/wishlist.v1.WishlistService/GetBookings"
)

// WishlistServiceClient is the client API for WishlistService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WishlistServiceClient interface {
	// Вишлисты
	CreateWishlist(ctx context.Context, in *CreateWishlistRequest, opts ...grpc.CallOption) (*WishlistResponce, error)
	GetWishlist(ctx context.Context, in *GetWishlistRequest, opts ...grpc.CallOption) (*WishlistResponce, error)
	GetUserWishlists(ctx context.Context, in *GetUserWishlistsRequest, opts ...grpc.CallOption) (*WishlistListResponce, error)
	UpdateWishlist(ctx context.Context, in *UpdateWishlistRequest, opts ...grpc.CallOption) (*WishlistResponce, error)
	DeleteWishlist(ctx context.Context, in *DeleteWishlistRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ListPublicWishlists(ctx context.Context, in *ListPublicWishlistsRequest, opts ...grpc.CallOption) (*WishlistListResponce, error)
	// Товары
	AddItem(ctx context.Context, in *AddItemRequest, opts ...grpc.CallOption) (*ItemResponce, error)
	GetItem(ctx context.Context, in *GetItemRequest, opts ...grpc.CallOption) (*ItemResponce, error)
	UpdateItem(ctx context.Context, in *UpdateItemRequest, opts ...grpc.CallOption) (*ItemResponce, error)
	DeleteItem(ctx context.Context, in *DeleteItemRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ListItems(ctx context.Context, in *ListItemsRequest, opts ...grpc.CallOption) (*ItemListResponce, error)
	// бронь
	BookItem(ctx context.Context, in *BookItemRequest, opts ...grpc.CallOption) (*ItemResponce, error)
	UnbookItem(ctx context.Context, in *UnbookItemRequest, opts ...grpc.CallOption) (*ItemResponce, error)
	GetBookings(ctx context.Context, in *GetBookingsRequest, opts ...grpc.CallOption) (*BookingListResponce, error)
}

type wishlistServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWishlistServiceClient(cc grpc.ClientConnInterface) WishlistServiceClient {
	return &wishlistServiceClient{cc}
}

func (c *wishlistServiceClient) CreateWishlist(ctx context.Context, in *CreateWishlistRequest, opts ...grpc.CallOption) (*WishlistResponce, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WishlistResponce)
	err := c.cc.Invoke(ctx, WishlistService_CreateWishlist_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wishlistServiceClient) GetWishlist(ctx context.Context, in *GetWishlistRequest, opts ...grpc.CallOption) (*WishlistResponce, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WishlistResponce)
	err := c.cc.Invoke(ctx, WishlistService_GetWishlist_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wishlistServiceClient) GetUserWishlists(ctx context.Context, in *GetUserWishlistsRequest, opts ...grpc.CallOption) (*WishlistListResponce, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WishlistListResponce)
	err := c.cc.Invoke(ctx, WishlistService_GetUserWishlists_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wishlistServiceClient) UpdateWishlist(ctx context.Context, in *UpdateWishlistRequest, opts ...grpc.CallOption) (*WishlistResponce, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WishlistResponce)
	err := c.cc.Invoke(ctx, WishlistService_UpdateWishlist_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wishlistServiceClient) DeleteWishlist(ctx context.Context, in *DeleteWishlistRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, WishlistService_DeleteWishlist_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wishlistServiceClient) ListPublicWishlists(ctx context.Context, in *ListPublicWishlistsRequest, opts ...grpc.CallOption) (*WishlistListResponce, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WishlistListResponce)
	err := c.cc.Invoke(ctx, WishlistService_ListPublicWishlists_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wishlistServiceClient) AddItem(ctx context.Context, in *AddItemRequest, opts ...grpc.CallOption) (*ItemResponce, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ItemResponce)
	err := c.cc.Invoke(ctx, WishlistService_AddItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wishlistServiceClient) GetItem(ctx context.Context, in *GetItemRequest, opts ...grpc.CallOption) (*ItemResponce, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ItemResponce)
	err := c.cc.Invoke(ctx, WishlistService_GetItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wishlistServiceClient) UpdateItem(ctx context.Context, in *UpdateItemRequest, opts ...grpc.CallOption) (*ItemResponce, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ItemResponce)
	err := c.cc.Invoke(ctx, WishlistService_UpdateItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wishlistServiceClient) DeleteItem(ctx context.Context, in *DeleteItemRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, WishlistService_DeleteItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wishlistServiceClient) ListItems(ctx context.Context, in *ListItemsRequest, opts ...grpc.CallOption) (*ItemListResponce, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ItemListResponce)
	err := c.cc.Invoke(ctx, WishlistService_ListItems_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wishlistServiceClient) BookItem(ctx context.Context, in *BookItemRequest, opts ...grpc.CallOption) (*ItemResponce, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ItemResponce)
	err := c.cc.Invoke(ctx, WishlistService_BookItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wishlistServiceClient) UnbookItem(ctx context.Context, in *UnbookItemRequest, opts ...grpc.CallOption) (*ItemResponce, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ItemResponce)
	err := c.cc.Invoke(ctx, WishlistService_UnbookItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wishlistServiceClient) GetBookings(ctx context.Context, in *GetBookingsRequest, opts ...grpc.CallOption) (*BookingListResponce, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BookingListResponce)
	err := c.cc.Invoke(ctx, WishlistService_GetBookings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WishlistServiceServer is the server API for WishlistService service.
// All implementations must embed UnimplementedWishlistServiceServer
// for forward compatibility.
type WishlistServiceServer interface {
	// Вишлисты
	CreateWishlist(context.Context, *CreateWishlistRequest) (*WishlistResponce, error)
	GetWishlist(context.Context, *GetWishlistRequest) (*WishlistResponce, error)
	GetUserWishlists(context.Context, *GetUserWishlistsRequest) (*WishlistListResponce, error)
	UpdateWishlist(context.Context, *UpdateWishlistRequest) (*WishlistResponce, error)
	DeleteWishlist(context.Context, *DeleteWishlistRequest) (*emptypb.Empty, error)
	ListPublicWishlists(context.Context, *ListPublicWishlistsRequest) (*WishlistListResponce, error)
	// Товары
	AddItem(context.Context, *AddItemRequest) (*ItemResponce, error)
	GetItem(context.Context, *GetItemRequest) (*ItemResponce, error)
	UpdateItem(context.Context, *UpdateItemRequest) (*ItemResponce, error)
	DeleteItem(context.Context, *DeleteItemRequest) (*emptypb.Empty, error)
	ListItems(context.Context, *ListItemsRequest) (*ItemListResponce, error)
	// бронь
	BookItem(context.Context, *BookItemRequest) (*ItemResponce, error)
	UnbookItem(context.Context, *UnbookItemRequest) (*ItemResponce, error)
	GetBookings(context.Context, *GetBookingsRequest) (*BookingListResponce, error)
	mustEmbedUnimplementedWishlistServiceServer()
}

// UnimplementedWishlistServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWishlistServiceServer struct{}

func (UnimplementedWishlistServiceServer) CreateWishlist(context.Context, *CreateWishlistRequest) (*WishlistResponce, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateWishlist not implemented")
}
func (UnimplementedWishlistServiceServer) GetWishlist(context.Context, *GetWishlistRequest) (*WishlistResponce, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWishlist not implemented")
}
func (UnimplementedWishlistServiceServer) GetUserWishlists(context.Context, *GetUserWishlistsRequest) (*WishlistListResponce, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserWishlists not implemented")
}
func (UnimplementedWishlistServiceServer) UpdateWishlist(context.Context, *UpdateWishlistRequest) (*WishlistResponce, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateWishlist not implemented")
}
func (UnimplementedWishlistServiceServer) DeleteWishlist(context.Context, *DeleteWishlistRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteWishlist not implemented")
}
func (UnimplementedWishlistServiceServer) ListPublicWishlists(context.Context, *ListPublicWishlistsRequest) (*WishlistListResponce, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPublicWishlists not implemented")
}
func (UnimplementedWishlistServiceServer) AddItem(context.Context, *AddItemRequest) (*ItemResponce, error) {
	return nil, status.Error(codes.Unimplemented, "method AddItem not implemented")
}
func (UnimplementedWishlistServiceServer) GetItem(context.Context, *GetItemRequest) (*ItemResponce, error) {
	return nil, status.Error(codes.Unimplemented, "method GetItem not implemented")
}
func (UnimplementedWishlistServiceServer) UpdateItem(context.Context, *UpdateItemRequest) (*ItemResponce, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateItem not implemented")
}
func (UnimplementedWishlistServiceServer) DeleteItem(context.Context, *DeleteItemRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteItem not implemented")
}
func (UnimplementedWishlistServiceServer) ListItems(context.Context, *ListItemsRequest) (*ItemListResponce, error) {
	return nil, status.Error(codes.Unimplemented, "method ListItems not implemented")
}
func (UnimplementedWishlistServiceServer) BookItem(context.Context, *BookItemRequest) (*ItemResponce, error) {
	return nil, status.Error(codes.Unimplemented, "method BookItem not implemented")
}
func (UnimplementedWishlistServiceServer) UnbookItem(context.Context, *UnbookItemRequest) (*ItemResponce, error) {
	return nil, status.Error(codes.Unimplemented, "method UnbookItem not implemented")
}
func (UnimplementedWishlistServiceServer) GetBookings(context.Context, *GetBookingsRequest) (*BookingListResponce, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBookings not implemented")
}
func (UnimplementedWishlistServiceServer) mustEmbedUnimplementedWishlistServiceServer() {}
func (UnimplementedWishlistServiceServer) testEmbeddedByValue()                         {}

// UnsafeWishlistServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WishlistServiceServer will
// result in compilation errors.
type UnsafeWishlistServiceServer interface {
	mustEmbedUnimplementedWishlistServiceServer()
}

func RegisterWishlistServiceServer(s grpc.ServiceRegistrar, srv WishlistServiceServer) {
	// If the following call panics, it indicates UnimplementedWishlistServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WishlistService_ServiceDesc, srv)
}

func _WishlistService_CreateWishlist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateWishlistRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WishlistServiceServer).CreateWishlist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WishlistService_CreateWishlist_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WishlistServiceServer).CreateWishlist(ctx, req.(*CreateWishlistRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WishlistService_GetWishlist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWishlistRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WishlistServiceServer).GetWishlist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WishlistService_GetWishlist_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WishlistServiceServer).GetWishlist(ctx, req.(*GetWishlistRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WishlistService_GetUserWishlists_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserWishlistsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WishlistServiceServer).GetUserWishlists(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WishlistService_GetUserWishlists_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WishlistServiceServer).GetUserWishlists(ctx, req.(*GetUserWishlistsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WishlistService_UpdateWishlist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateWishlistRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WishlistServiceServer).UpdateWishlist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WishlistService_UpdateWishlist_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WishlistServiceServer).UpdateWishlist(ctx, req.(*UpdateWishlistRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WishlistService_DeleteWishlist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteWishlistRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WishlistServiceServer).DeleteWishlist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WishlistService_DeleteWishlist_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WishlistServiceServer).DeleteWishlist(ctx, req.(*DeleteWishlistRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WishlistService_ListPublicWishlists_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPublicWishlistsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WishlistServiceServer).ListPublicWishlists(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WishlistService_ListPublicWishlists_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WishlistServiceServer).ListPublicWishlists(ctx, req.(*ListPublicWishlistsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WishlistService_AddItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WishlistServiceServer).AddItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WishlistService_AddItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WishlistServiceServer).AddItem(ctx, req.(*AddItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WishlistService_GetItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WishlistServiceServer).GetItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WishlistService_GetItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WishlistServiceServer).GetItem(ctx, req.(*GetItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WishlistService_UpdateItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WishlistServiceServer).UpdateItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WishlistService_UpdateItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WishlistServiceServer).UpdateItem(ctx, req.(*UpdateItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WishlistService_DeleteItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WishlistServiceServer).DeleteItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WishlistService_DeleteItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WishlistServiceServer).DeleteItem(ctx, req.(*DeleteItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WishlistService_ListItems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListItemsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WishlistServiceServer).ListItems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WishlistService_ListItems_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WishlistServiceServer).ListItems(ctx, req.(*ListItemsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WishlistService_BookItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BookItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WishlistServiceServer).BookItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WishlistService_BookItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WishlistServiceServer).BookItem(ctx, req.(*BookItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WishlistService_UnbookItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnbookItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WishlistServiceServer).UnbookItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WishlistService_UnbookItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WishlistServiceServer).UnbookItem(ctx, req.(*UnbookItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WishlistService_GetBookings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBookingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WishlistServiceServer).GetBookings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WishlistService_GetBookings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WishlistServiceServer).GetBookings(ctx, req.(*GetBookingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WishlistService_ServiceDesc is the grpc.ServiceDesc for WishlistService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WishlistService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "wishlist.v1.WishlistService",
	HandlerType: (*WishlistServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateWishlist",
			Handler:    _WishlistService_CreateWishlist_Handler,
		},
		{
			MethodName: "GetWishlist",
			Handler:    _WishlistService_GetWishlist_Handler,
		},
		{
			MethodName: "GetUserWishlists",
			Handler:    _WishlistService_GetUserWishlists_Handler,
		},
		{
			MethodName: "UpdateWishlist",
			Handler:    _WishlistService_UpdateWishlist_Handler,
		},
		{
			MethodName: "DeleteWishlist",
			Handler:    _WishlistService_DeleteWishlist_Handler,
		},
		{
			MethodName: "ListPublicWishlists",
			Handler:    _WishlistService_ListPublicWishlists_Handler,
		},
		{
			MethodName: "AddItem",
			Handler:    _WishlistService_AddItem_Handler,
		},
		{
			MethodName: "GetItem",
			Handler:    _WishlistService_GetItem_Handler,
		},
		{
			MethodName: "UpdateItem",
			Handler:    _WishlistService_UpdateItem_Handler,
		},
		{
			MethodName: "DeleteItem",
			Handler:    _WishlistService_DeleteItem_Handler,
		},
		{
			MethodName: "ListItems",
			Handler:    _WishlistService_ListItems_Handler,
		},
		{
			MethodName: "BookItem",
			Handler:    _WishlistService_BookItem_Handler,
		},
		{
			MethodName: "UnbookItem",
			Handler:    _WishlistService_UnbookItem_Handler,
		},
		{
			MethodName: "GetBookings",
			Handler:    _WishlistService_GetBookings_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/proto/wishlists/v1/wishlists.proto",
}
