env: "local" # local, dev, env

grpc:
  port: "50052" # self port
  auth_service_addr: "localhost"
  auth_service_port: "50051"

storage:
  host: "localhost"
  port: "5432"
  db: "postgres"
  user: "postgres"
  password: "0000"

kafka:
  broker: "localhost:9092"
  topic: "wishlist_events"

logbull:
  url: "localhost"
  port: "4005"
  project_id: ""
