env: "local" # local, dev, env

kafka:
  broker_url: "localhost"
  broker_port: "9092"
  topic: "wishlist_events"
  group_id: "notification_group"
  
logbull:
  url: "localhost"
  port: "4005"
  project_id: ""

smtp:
  host: "smtp.gmail.com"
  port: "587"
  user: "usrEmail@gmail.com"
  password: "userPwd"
  from: "notifications@wishlist.app"